/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // https://guides.gradle.org/building-java-web-applications/
    war

    id("com.github.ben-manes.versions") version "0.21.0"
    id("io.freefair.lombok") version "3.2.1"
    id("org.gretty") version "2.3.1"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    providedCompile("com.google.code.gson:gson:2.8.5")
    providedCompile("com.google.inject:guice:4.2.2")
    providedCompile("com.google.inject.extensions:guice-servlet:4.2.2")
    providedCompile("javax.servlet:javax.servlet-api:4.0.1")
    providedCompile("javax.websocket:javax.websocket-api:1.1")
    providedCompile("org.apache.logging.log4j:log4j-api:2.11.2")
    providedCompile("org.apache.logging.log4j:log4j-core:2.11.2")
    providedCompile("org.apache.logging.log4j:log4j-slf4j18-impl:2.11.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.1.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.1.0")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

gretty {
    servletContainer = "tomcat9"
    logbackConfigFile = "gretty-logback.xml"
}
