/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // https://guides.gradle.org/building-java-web-applications/
    war

    id("org.gretty") version "2.3.1"
    id("io.freefair.lombok") version "3.2.0"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    providedCompile("javax.servlet:javax.servlet-api:3.1.0")
    providedCompile("org.apache.logging.log4j:log4j-api:2.11.2")
    providedCompile("org.apache.logging.log4j:log4j-core:2.11.2")
    providedCompile("org.apache.logging.log4j:log4j-slf4j18-impl:2.11.2")
    testCompile("junit:junit:4.12")
}

gretty {
    servletContainer = "jetty9.4"
}
